name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build for Windows
      run: env GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -v -H=windowsgui"
      
    - name: Build for Linux
      run: env GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -v -H=windowsgui"
