name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build for Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -ldflags "-s -w -v -H=windowsgui"
      
    - name: Build for Linux
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -ldflags "-s -w -v"

    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./assets
        asset_name: image-uploader-v${{ github.run_number }}.exe
        asset_content_type: application/octet-stream
